### ISSUE TITLE
Visual glitches in folders with files named "Icon."

### ISSUE THREAD

**Issue by eugenesan** [drdo/redu#39]
I've noticed that when files named "Icon." exist in the folder, the line of the file is not cleared and characters from previous screen remains on the line.

Also when the line with the file is selected it becomes completely empty while still displaying details in the pop-up.

Those files appear in Dropbox folders on old OSX versions (circa 2014).
Actual file name is:
```
`Icon'$'\r'
```
or in hex
```
00000000  49 63 6f 6e 0d 0a                                 |Icon..|
00000006
```

P.S.
I didn't notice any issues with regular unicode and legacy encodings, even with Right-to-Left languages ;-)
So the issues seems to be specific to filenames containing "control" characters and might be in one of the libraries used by redu.

P.P.S
After thinking about it, I am not sure if it would possible to "Mark" those files and pass to restic.
So maybe they should be just ignored since they are taking zero space.

**Comment by drdo** [comment]
I've reproduced the issue and confirm that this is a problem.

There are two things here:
- Escaping control characters when displaying so we don't mess things up visually
- Escaping special characters into a format that works on a restic exclude file (https://pkg.go.dev/path/filepath#Match)

**Comment by drdo** [comment]
1 is easily solvable but I don't think 2 can be fully solved while keeping the exclude-file compatible output.

I was looking at restic's exclude file parsing code and I believe there is no way to match a newline in the filename

**Comment by eugenesan** [comment]
Thank you.
If it's too much work to add those files to exclusion list, I think displaying those files as "grayed out" might be a good solution.

**Comment by drdo** [comment]
I have a solution which seems to work, the only problem is that the exclude file will look a bit strange when view with standard text tools if you have carriage returns or newlines.

But it appears to work, with restic doing the right thing when passed that exclude file.

It seems like a good solution, if you have carriage returns and newlines in your filenames you are doing something odd anyway :)

**Comment by drdo** [comment]
I've opened the PR (#40). Could you possibly test it with your repo and let me know how it works?

**Comment by eugenesan** [comment]
Thank you.
Works as expected.

redu shows the file as:
```
0 B                  Icon\r
```
in exclude file it appears as:
```
/Dropbox/Icon[^^@-^L^N-.]
```

restic successfully removed the file:
```
excluding /Dropbox/Icon
saved new snapshot 791a6238
removed old snapshot 4d7f2fc4
```

**Comment by drdo** [comment]
Thank you. Merging the PR.
