### ISSUE TITLE
'l' shortcut to enter a directory doesn't work

### ISSUE THREAD

**Issue by rluetzner** [drdo/redu#52]
The usual Vim-motions `h`,`j` and `k` work perfectly fine, but `l` seems to be unmapped. I can enter a directory with the right arrow, wheras I can leave a directory with left arrow and `h`.

I'm using redu 0.2.3.

**Comment by drdo** [comment]
Hello! Thank you for the kind words and for the bug report.

This is definitely a bug! I can't believe this was like that for this long. I'll push a fix soon.

**Comment by drdo** [comment]
The fix is now released in 0.2.4.

**Comment by rluetzner** [comment]
Weird. Did you manage to verify that this works now? I just built the latest 'main' branch and it still doesn't work. 🤔  I'll double-check that and report back.

**Comment by rluetzner** [comment]
Nevermind, I'm an idiot. I accidentally ran the wrong binary...
