### ISSUE TITLE
redu prompts for password or password file, even though RESTIC_PASSWORD env variable is set

### ISSUE THREAD

**Issue by rluetzner** [drdo/redu#55]
This seems like it broke between 0.2.3 and 0.2.4. I guess the parameter was optional before and is now required or at least it doesn't recognize that RESTIC_PASSWORD is already set.

Here's the error message and what I did

```
❯  cat restic-azure.env
export AZURE_ACCOUNT_NAME="xyz"
export AZURE_ACCOUNT_KEY="azure_pass"
export RESTIC_REPOSITORY="azure:restic-repo:/"
export RESTIC_PASSWORD="repo_password"

❯  source restic-azure.env

❯  redu
error: the following required arguments were not provided:
  <--password-command <COMMAND>|--password-file <FILE>>

Usage: redu <--repo <REPO>|--repository-file <REPOSITORY_FILE>> <--password-command <COMMAND>|--password-file <FILE>>

For more information, try '--help'.
```

When I go back to 0.2.3 it works as expected.

**Comment by rluetzner** [comment]
I tried figuring out what happened, but I'm not familiar with Rust. It's obvious that `Option<string>` has been changed for the config parameters, but I wouldn't know how to fix this. I guess it would be best to check the environment for them. This might already happen somewhere as I only looked at the diff and not the entire code yet.

**Comment by drdo** [comment]
What happened was we started checking if one of `--password-command` or `--password-file` were set (or their respective variables) instead of them being optional (to try to catch missing passwords right away instead of failing later when spawning the restic processes).

**Comment by rluetzner** [comment]
I've actually got a fix for it. Let me send you a pull request and have a look if you'd want that. 🙂
