### ISSUE TITLE
Error: too many terms in compound SELECT when running redu with more than 500 restic snapshots

### ISSUE THREAD

**Issue by bottomquark** [drdo/redu#62]
When running redu on a restic repo containing more than 500 snapshots, redu does not start but produces an error
``` 
(●    ) Getting restic config                                                                                         Using cache file "/[REDACTED]/.cache/redu/0f149918ce61c0ab2eaf374de39951d23e5c70c747222be8ebe296350cf4eb5c.db"
 (●    ) Fetching repository snapshot list
Error: too many terms in compound SELECT

Caused by:
    Error code 1: SQL error or missing database
```

The (hard) limit for compound select is 500 according to https://www.sqlite.org/limits.html and an SQL statement in redu seems to use the number of snapshots in a select statement.

To reproduce, run in an empty directory (if using Linux/Bash):
```
#!/bin/bash

export PATH=$PWD:$PATH
export RESTIC_PASSWORD="asdf"

if [ ! -e ./restic ]
then
        wget https://github.com/restic/restic/releases/download/v0.17.0/restic_0.17.0_linux_amd64.bz2
        bzip2 -d restic_0.17.0_linux_amd64.bz2
        mv ./restic_0.17.0_linux_amd64 restic
        chmod +x ./restic
        rm ./restic_0.17.0_linux_amd64.bz2
fi

if [ ! -e ./repo ]
then
        restic init --repo ./repo
fi

if [ $(ls -1 ./repo/snapshots | wc -l) -lt 501 ]
then
        for i in {0..501}
        do
                echo "creating snapshot $i"
                restic backup --quiet --exclude repo $PWD --repo ./repo
        done
fi

./redu-0.2.5-linux-x86_64 -r ./repo
```

**Comment by drdo** [comment]
Thank you for the report!

This does seem like a problem.

The simplest solution is probably to do the sqlite query for each snapshot separately and not rely on sqlite to combine everything itself.

**Comment by drdo** [comment]
The entries for each snapshot are in a different table because otherwise insertions get very slow as the table gets bigger.

I've considered just embracing this separation and putting each snapshot on its own file. This would greatly speed up snapshot deletion.

**Comment by drdo** [comment]
@bottomquark If you want to try it out or do some review there's a fix available on #63 :)

**Comment by bottomquark** [comment]
Thanks, checked out the branch and built redu for testing. It now starts and displays data of my 650 snapshots. I am sadly not qualified to do reviews on Rust code, I just can roughly understand what it may be doing ;)

**Comment by drdo** [comment]
Great, thank you :)
