### ISSUE TITLE
Missing Page-Up / Page-Down key shortcuts

### ISSUE THREAD

**Issue by eugenesan** [drdo/redu#8]
First, thank you for a very useful tool!

I find it very tedious to scroll thru long lists of files/folders using only Up/Down keys.
It would be really nice to use Pg-Up/Dn keys or existing shortcuts with CTRL to accelerate.

**Comment by drdo** [comment]
Hey!

That's a great suggestion, I'll definitely implement something like that.

What do you think about PgUp/PgDown, C-b/C-f and C-u/C-d?

**Comment by eugenesan** [comment]
> Hey!
> 
> That's a great suggestion, I'll definitely implement something like that.
> 
> What do you think about PgUp/PgDown, C-b/C-f and C-u/C-d (the last two vim-style)?

II think C-u/C-d is not necessary needed and will only add to possible shortcut conflicts.
