### ISSUE TITLE
Missing confirmation dialogs on "clear all marks" and "save on exit"

### ISSUE THREAD

**Issue by eugenesan** [drdo/redu#9]
Currently, simple "c" press will cause irreversible loss of all marks.

I suggest:
1. Adding confirmation dialog when clearing marks
2. Either add manual save as a shortcut or ask to save when exiting.

**Comment by drdo** [comment]
Hello.

1. I agree, this would be nice to have.
2. I don't follow. Right now marks are never cleared on exit, they can only be remove with 'u' or 'c'.

**Comment by eugenesan** [comment]
On point 2,
I meant that if you accidentally cleared all marks or just want to ignore the changes in current session, it would be nice to have a prompt to confirm savings of the changes when exiting.

**Comment by eugenesan** [comment]
Thanks!
